### ISSUE TITLE
Cannot see the output in the Execution

### ISSUE THREAD

**Issue by Delta456** [mikeleppane/go-explorer#18]
I cannot see the output in the execution area and I cannot even scroll down to see it.

![image](https://user-images.githubusercontent.com/28479139/149629233-f004cbe2-e07b-46ad-b0ce-dbac2037e141.png)

Anyways this work is wonderful!

**Comment by mikeleppane** [comment]
Thanks for the feedback! 
Okay, I have not witnessed such behavior. I've used this with relatively new Firefox, Chrome, and Edge. Firstly, could you tell which browser you are using. The overflow property is not set at the moment (because to me it does not look great) so that might cause this.

**Comment by Delta456** [comment]
I am on the latest version of FireFox and I am using Windows 10.

![image](https://user-images.githubusercontent.com/28479139/149944016-b0f990c6-9d65-409d-b9c5-f7f290f9804c.png)

**Comment by mikeleppane** [comment]
Okay. Now I know what's the issue. Obviously, you can always drag that "Execution" view slightly higher but that's probably not what you want and not the optimal solution.  Needs to be fixed.

Thanks!

**Comment by mikeleppane** [comment]
The issue should be now fixed.
